### ISSUE TITLE
Extract MSG extended properties like VotingOptions and VotingResponse

### ISSUE THREAD

**Issue by markb-trustifi** [HiraokaHyperTools/msgreader#13]
MSG file may have also extended properties:
https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxomsg/87488eff-3eec-4502-bc94-2368c04e3109

- PidLidVerbStream - VotingOptions
- PidLidVerbResponse - VotingResponse

**Comment by kenjiuno** [comment]
Hi.
It seems that there is a big task (currently not implemented) for decoding [[MS-OXMSG]: Named Property Mapping Storage | Microsoft Docs](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxmsg/193c169b-0628-4392-aa51-83009be7d71f) before we reach PidLidVerbStream/PidLidVerbResponse.
This will take a while.

**Comment by kenjiuno** [comment]
ok recently published 1.7.1 will parse it.

- https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.FieldsData.html#votingOptions
- https://github.com/HiraokaHyperTools/msgreader/blob/49ea9a46182832dbc0155aaf7bee69504947c25a/test/voteItems.json#L23
- https://github.com/HiraokaHyperTools/msgreader/blob/49ea9a46182832dbc0155aaf7bee69504947c25a/test/voteYes.json#L18
