### ISSUE TITLE
Distinguish between images attached and imaged nested in the body mail

### ISSUE THREAD

**Issue by DevPan29** [HiraokaHyperTools/msgreader#14]
Hi @kenjiuno ,
this is not an issue but a question: sometimes an email can have images inside the body mail and images as attachments.
I would like to know how to distinguish these two kind of attachments.
I though that images in the body mail would have _pidContentId_ field , infact I use that field to find _cid:_ related and substitute it in the body mail with _data:image/jpg;base64,_ conversion.
Unfortunately also attached images has _pidContentId_ but them shouldn't be inserted in the body mail.

How can I distinguish these two kind of images?

Kind regards.

**Comment by kenjiuno** [comment]
Hi.
[PidTagAttachmentHidden Canonical Property | Microsoft Docs](https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/pidtagattachmenthidden-canonical-property) will be possible data.

1.6.6 has been published and this will extract it:

- https://www.npmjs.com/package/@kenjiuno/msgreader
- https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.FieldsData.html#attachmentHidden
- https://github.com/HiraokaHyperTools/msgreader/blob/77bebe10c2688b3e76eeab556bfefcecc975e0bb/test/attachAndInline.json#L14-L24

**Comment by DevPan29** [comment]
Hi @kenjiuno ,
thank you for your answer.
It works correctly :-).

Kind regards.
Alessandro

**Comment by rakeshrio** [comment]
Hi @kenjiuno ,

{
            "dataType": "attachment",
            "extension": ".png",
            "name": "abz-logo-gray-green.png",
            "fileName": "abz-logo-gray-green.png",
            "dataId": 167,
            "contentLength": 23719,
            "fileNameShort": "abz-lo~1.png",
            "pidContentId": "abz-logo-gray-green.png@SNC.ff224570c491543c",
            "creationTime": "Tue, 09 May 2023 11:56:21 GMT",
            "lastModificationTime": "Tue, 09 May 2023 11:56:21 GMT",
            "attachmentHidden": true,
           "dataUrl": "blob:http://localhost:9091/b6c03749-6c9c-4cbf-9bde-73d33ef8e694"
}.   

Iam getting dataURL but if its not working its showing undefined when i paste in search url pf browser, is there any other way to extract the attachment. Thanks in advance
