### ISSUE TITLE
How can I get attachment creation date?

### ISSUE THREAD

**Issue by wcstco** [HiraokaHyperTools/msgreader#16]
Hi, please explain me how to get attachment creation date.

**Comment by kenjiuno** [comment]
Hi thanks for catching this.

The published `1.8.1-alpha.1` will parse them:

- https://github.com/HiraokaHyperTools/msgreader/blob/da47eee096492ad327dff33f170c467d37efc136/test/attachAndInline.json#L12-L13
- https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.FieldsData.html#lastModificationTime
- https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.FieldsData.html#creationTime

**Comment by wcstco** [comment]
Thank you. Got it.

**Comment by kenjiuno** [comment]
Thanks! now closing.
