### ISSUE TITLE
subject with ( 畑㵲応ｲ瑤㵨㠱 ) UTF Characters becomes as ???

### ISSUE THREAD

**Issue by mynpmpackage** [HiraokaHyperTools/msgreader#17]
if subject has utf symbols / 畑㵲応ｲ瑤㵨㠱 then subject is becoming as ??? , 

tried with node cli parse 

![image](https://user-images.githubusercontent.com/88725851/134709904-973ac6c1-eeaa-47c5-9c7c-36fcbc816e99.png)

Could you please help how to enable support for utf symbols in parser

**Comment by kenjiuno** [comment]
Hi.
I need the sample to verify, could you please supply the msg you have tested to mail `ku@digitaldolphins.jp`?

**Comment by mynpmpackage** [comment]
it is a normal email having empty email body by only having subject with these characters 畑㵲応ｲ瑤㵨㠱 

Used node cli parser and cli parses and gives us ???

**Comment by kenjiuno** [comment]
Ok

And then, what kind of OS are you using?

At least Japanese Windows 10 seems to process (decode and display) the subject having Unicode-specific characters.

![2021-09-26_21h53_46](https://user-images.githubusercontent.com/5955540/134808885-496db273-240b-4c8e-9620-5860d531779e.png)

Or it may be the problem of the console display capability.

Try: `node cli parse test\unicode1.msg > output.txt`

And then observe `output.txt` in GUI text editor other than the console.

**Comment by mynpmpackage** [comment]
You are correct, I see the characters are being read in output.txt

There is no issue with the parser and we can close this defect.

Thank you so much for quick response.
