### ISSUE TITLE
Getting type of email like calendar, notes

### ISSUE THREAD

**Issue by satishs37** [HiraokaHyperTools/msgreader#18]
Is there any possibility to get the type of email? Like, whether email is calender ,invite email, or notes or normal email

**Comment by kenjiuno** [comment]
Hi.
I'm not professional of `msg` file. Could you describe the detail of them? `calender`, `invite email`, `notes`, or `normal`.

**Comment by mynpmpackage** [comment]
Calendar/Invite => 

> Opened outlook calendar and dragged out an email to desktop
> Trying to read the .msg file from desktop using msgreader
> MsgReader will parse email correctly as it is .msg

Here, i am trying to get some properties which says this is not an email sent from others and this is a calendar invite. 

Below are the validations I check using the parsed properties to differentiate emails from Meeting Invites, Notes 

To try this validation and to allow only emails sent from others as **success** case.

```
if (
        // Notes and Email Contacts
        emailItem.creatorSMTPAddress === undefined &&
        emailItem.senderName === undefined &&
        emailItem.senderEmailAddress === undefined &&
        emailItem.headers === undefined &&
        emailItem.emailRecipients === ''
      ) {
        return {
          emailType: EmailType.invalid,
          emailSubject: emailEntity.emailSubject,
        };
      }
```

**Comment by mynpmpackage** [comment]
Thanks for quick fix. 

Will check the build and let you know asap.

**Comment by kenjiuno** [comment]
@mynpmpackage Please check the version of tools,

```bat
H:\Proj\msgreader>node -v
v14.17.3

H:\Proj\msgreader>yarn tsc -v
yarn run v1.22.4
$ H:\Proj\msgreader\node_modules\.bin\tsc -v
Version 4.4.4
Done in 0.34s.

H:\Proj\msgreader>yarn -v
1.22.4
```

**Comment by kenjiuno** [comment]
I wonder about part `../../node_modules/@types/inquirer/index.d.ts` in output.

Please try latest `master` branch. It is https://github.com/HiraokaHyperTools/msgreader/commit/84942ec98ab6a40fcf05bda82a97ba97fec0d24a

This fix contains advices imported from:

- https://stackoverflow.com/a/37568841
- [TypeScript: TSConfig Reference - Docs on every TSConfig option](https://www.typescriptlang.org/tsconfig#typeRoots)

**Comment by mynpmpackage** [comment]
Thanks for publishing new version. 

We can close this request/issue.
