### ISSUE TITLE
Some .msg attachments cannot be opened with MS Outlook

### ISSUE THREAD

**Issue by GTCrais** [HiraokaHyperTools/msgreader#22]
#### Example scenario:
- **EmailOne** has attachments, of which some are also `.msg`, which also have other attachments (PDFs etc.)
```
EmailOne.msg
--- SomeDocument.pdf
--- OtherDocument.pdf
--- AttachedEmail.msg
------ FooDocument.pdf
------ BarDocument.pdf
```
- after parsing **EmailOne** and saving **AttachedEmail.msg** to disk, I cannot open **AttachmedEmail.msg** with MS Outlook
```
Cannot start Microsoft Outlook. We can't open 'C:\path\to\document\AttachedEmail.msg'. 
It is possible the file is already open, or you don't have permission to open it.

To check your permissions, right-click the file folder, then click Properties.
```
- these attachments, however, **can** be parsed using `msgreader`, and their attachments (PDFs etc.) can be saved to disk, and opened in PDF viewer etc -- in our Example scenario, `FooDocument.pdf` and `BarDocument.pdf` would be normally saved and usable.

This is **not** a permission issue, and the file is **not** already open. 

This issue also does not happen with all emails which have .msg attachments, only some. Link to an example email provided at the bottom of the issue description.

#### After further testing:
- v1.9.0 - no issue
- v1.10.0 - no issue
- v1.11.0 - no issue
- **v1.12.0-alpha.1 - issue appears**

https://github.com/HiraokaHyperTools/msgreader/commit/81edcca6a147ebfcecd97b36304852c8cbb18926 - this must be the commit that started causing this

### Here's an example email whose .msg attachment breaks - [download](https://bit.ly/3c0MfN6)

**Comment by kenjiuno** [comment]
Thanks for reporting this.
I could reproduce the open error problem by Outlook 2013 (using saved inner msg).

I wrote a flow that is useful to discuss about broken part of msgreader. This will be `Case 2. Maybe bug in **structure handling**`.

![how-to](https://user-images.githubusercontent.com/5955540/141237901-cbafe279-6ad7-47da-8245-8d40f698e9ef.png)

**Comment by kenjiuno** [comment]
No, this is bug of `Burner` mentioned at https://github.com/HiraokaHyperTools/msgreader/commit/81edcca6a147ebfcecd97b36304852c8cbb18926

This awful mistake https://github.com/HiraokaHyperTools/msgreader/commit/79bb367a3ddd10c222e80a2aacb8c728f1eaa078 was fixed right away on `1.13.0-alpha.1`

I'll search CFBF validation tool for detecting this kind of cases.

**Comment by kenjiuno** [comment]
Ok I have written simple Win32 `ValidateCompoundFile.exe` https://github.com/HiraokaHyperTools/ValidateCompoundFile/blob/master/main.cpp

```
H:\Proj\msgreader> tools\ValidateCompoundFile.exe "X:\msgreader\22\BROKEN Test child email.msg"
StgOpenStorageEx returned 0x80030109

H:\Proj\msgreader> tools\ValidateCompoundFile.exe "X:\msgreader\22\Test child email.msg"
StgOpenStorageEx returned 0x00000000
```

[StgOpenStorageEx function](https://docs.microsoft.com/en-us/windows/win32/api/coml2api/nf-coml2api-stgopenstorageex) will be usable to detect broken archives generated by `v1.12.0-alpha1`.

`%ERRORLEVEL%` is returned like generic Unix tool. Usage: `ValidateCompoundFile.exe a.msg && echo OK || echo ERROR`

And included tests can be run by `yarn` command.

**Comment by kenjiuno** [comment]
I'll publish `1.13.0` in some days if there is no more further side effect (or bug report).

**Comment by GTCrais** [comment]
Thanks for fixing this. Unfortunately, this fix introduced another bug - https://github.com/HiraokaHyperTools/msgreader/issues/23

**Comment by GTCrais** [comment]
After thorough testing, I can confirm this has been fixed. Closing the issue.

Thanks for the fix!
