### ISSUE TITLE
parsing email to recipients when more than 200

### ISSUE THREAD

**Issue by mynpmpackage** [HiraokaHyperTools/msgreader#24]
I see below observation in v1.10.0 and not as a defect/issue,
When an email **to** recipients list is more than 200, then parsing all the recipients in loop takes time and delays the parsed result.  Could you please help me to understand if this observation is a known one already or any workaround that fixes the delay?

I used version v1.13.0 cli parser with email containing 200 **to** recipients

**Comment by kenjiuno** [comment]
Ok it will be better now: `1.14.0-alpha.1`

> When an email **to** recipients list is more than 200

Having 200 recipients will be possible case on some reasons. I'm surprised that msg file size grows up to `578 KB`

I have found redundant code with Chrome DevTools and fixed: https://github.com/HiraokaHyperTools/msgreader/commit/4ae72d325313211abf5cc48fce93d5ea10520918

![2021-11-23_09h51_09](https://user-images.githubusercontent.com/5955540/142956449-d0834014-88c8-4a8b-be3d-1f2ffbac5dd6.png)

**Comment by mynpmpackage** [comment]
Thanks for the fix,
I will use 1.14.0-alpha.1 and check again.

**Comment by mynpmpackage** [comment]
Thanks, **Provided alpha fix** avoided delay and **got working**. 

Sorry for delay, I got released alpha package updated an hour before in our internal server,  No delay observed with build 1.14.0-alpha.1, checked with the email which contain 300 and more to recipients

Could you please release build 1.14.0

**Comment by kenjiuno** [comment]
Ok `1.14.0` has published just now.

**Comment by mynpmpackage** [comment]
Thank you.

**Comment by kenjiuno** [comment]
Ok now closing
