### ISSUE TITLE
bodyHTML not getting in response

### ISSUE THREAD

**Issue by loveena-zenya** [HiraokaHyperTools/msgreader#25]
I want to have bodyHtml or html in response but i am only getting body text.Please help me.

**Comment by kenjiuno** [comment]
Hi
Majority msg files contain only `compressedRtf` and `text`.
https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.FieldsData.html#compressedRtf
https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.FieldsData.html#body

It needs decompressor and converter.

`compressedRtf` will be restored to decompressed RTF by using `@kenjiuno/decompressrtf` or such.
https://www.npmjs.com/package/@kenjiuno/decompressrtf

This is a sample of decompressed RTF. Could you see some html tags exists in rtf?
https://github.com/HiraokaHyperTools/msgreader/blob/master/test/sent.rtf

Although generic purpose converters (rtf to html) will be found by searching around npmjs, this decompressed RTF seems to apply special specification: [Rich Text Format (RTF) Extensions Algorithm](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxrtfex/411d0d58-49f7-496c-b8c3-5859b045f6cf).

See also [[MS-OXRTFEX]: De-Encapsulating RTF Reader Algorithm Details | Microsoft Docs](https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxrtfex/4b2cae33-9f3a-4c9f-8901-1141921cc0af)

By googling, I found this converter may be possible to deal with RTF-encapsulated formats.
[rtf-stream-parser - npm](https://www.npmjs.com/package/rtf-stream-parser)
