### ISSUE TITLE
Sent property 

### ISSUE THREAD

**Issue by mynpmpackage** [HiraokaHyperTools/msgreader#26]
Like **MailItem.Sent**([https://docs.microsoft.com/en-us/office/vba/api/outlook.mailitem.sent]) , 

Could you please help me knowing which msgreader [fieldsdata()](https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.FieldsData.html) parsed property represents **Sent**?.  Sometimes this property **Sent** help me to decide the email is draft when Sent flag is set to false. 

Is it possible to add Sent property to  https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.FieldsData.html?

Will the **[PidTagMessageFlags](PidTagMessageFlags)** will help us when mfUnsent is not set?

**Comment by kenjiuno** [comment]
Thanks, _messageFlags_ will be exposed since `1.14.1-alpha.1`

- https://www.npmjs.com/package/@kenjiuno/msgreader
- https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.SomeOxProps.html#messageFlags
- https://github.com/HiraokaHyperTools/msgreader/blob/e213335ce1c94609c414823170a3b6556c13cb85/test/sent.json#L23

**Comment by mynpmpackage** [comment]
Thank you for exposing. 
I will check with 1.14.1-alpha.1 and confirm back.

**Comment by mynpmpackage** [comment]
As usual I am having local server cache issue and it will take few more hours to get the cache updated with 1.14.1-alpha.1 .  

For now, I tried with node cli parse command with the emails in draft box and seeing different values and not 8, Do you know why?

Below are the steps I tried.

1. Tried Re composing email from inbox and saved as Draft
2.  Drag and Dropped email from draft box to file system folder
3.  Executed node cli parse on the copied email in system folder
4.  MessageFlags value is not 8 and it gives different values like 17 or 45 and so on.

**Comment by kenjiuno** [comment]
_messageFlags_ are bit fields.

![2022-01-31_21h14_06](https://user-images.githubusercontent.com/5955540/151792075-a87ec58c-5cfe-4ce4-ad1e-1bca3d0fd1c2.png)

To extract _mfUnsent_ flag, try Bitwise AND operator. [Bitwise AND (&) - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_AND)

**Comment by mynpmpackage** [comment]
Okay thanks. 
Does it mean, we have to check parsed messageFlags values with Bitwise AND operator to derive for draft(unsent)? And if 8 then we have consider as draft email?

**Comment by kenjiuno** [comment]
Although with some coding msgreader can include sent field, imo it'd be cool if we can handle bit flag processing on local code.

```js
// boolean
const sent = (messageFlags & 8) == 0;
const unsent = (messageFlags & 8) != 0;
```

**Comment by mynpmpackage** [comment]
Okay, thanks. I will put in local code.

**Comment by mynpmpackage** [comment]
Verified with alpha it works, could you please release the version 1.14.1.

**Comment by kenjiuno** [comment]
Ok `1.14.1` is now ready

**Comment by mynpmpackage** [comment]
Thank You. I am going to use 1.14.1.

Thanks for the quick fix.
