### ISSUE TITLE
Difficulty running in browser

### ISSUE THREAD

**Issue by flashgorton** [HiraokaHyperTools/msgreader#29]
Hi, 

Thanks for your amazing work on this project. 

I'm having some difficulty getting this running in the browser. Could you please share the code of the demo site at https://hiraokahypertools.github.io/msgreader_demo/ ? 

Thanks in advance, 

flashgorton

**Comment by flashgorton** [comment]
I have resolved this now. The problem was not with your code. 

Best wishes.

**Comment by kenjiuno** [comment]
OK...

FYI this is source repository of that demo site https://github.com/HiraokaHyperTools/msgreader_demo
