### ISSUE TITLE
Missing informations in converted mails

### ISSUE THREAD

**Issue by bahamut657** [HiraokaHyperTools/msgreader#30]
Hi and good job for this work.
I'm using the last version of this lib(1.11), and I notice these missing informations in the output mail:

- No Received Date and time is included in converted (EML) mail. This info is very useful 
- In case the MSG is including the img HTML tag to show inline image, in the converted email I found [https://MYLINK]

Is it possible to include these informations in the converted mail?
Best Regards

**Comment by kenjiuno** [comment]
> No Received Date and time is included in converted (EML) mail. This info is very useful

If you are trying to use [eml-format](https://github.com/papnkukn/eml-format)'s build method with output from msgreader, adapter is required.

About received date:

```
    headers: {
        "Date": msgInfo.clientSubmitTime,
    }
```

clientSubmitTime: https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.SomeOxProps.html#clientSubmitTime

**Comment by bahamut657** [comment]
Thank you so much. I missed this useful documentation page.
I close that issue.
