### ISSUE TITLE
MsgReader is not a constructor

### ISSUE THREAD

**Issue by nandolopez** [HiraokaHyperTools/msgreader#31]
When I try to use the library with pure node (no frameworks. I have the following error:

const Reader = new MsgReader(msgFileBuffer)
                   ^

TypeError: MsgReader is not a constructor
 

Do you have any idea or could you fix it?: 

My code: 
const msgFileBuffer = fs.readFileSync(FileToAnalyze)
const Reader = new MsgReader(msgFileBuffer)
const Data = Reader.getFileData()
console.log(Data.subject)

**Comment by kenjiuno** [comment]
Hi, could you try adding `.default` on require?

```
const MsgReader = require('@kenjiuno/msgreader').default;
```

**Comment by PedroS5499** [comment]
keep happening
