### ISSUE TITLE
{dataType: null, error: 'Unsupported file type!'}

### ISSUE THREAD

**Issue by TegidVeol** [HiraokaHyperTools/msgreader#33]
Hi there,

when parsing a simple Outlook Email (Ofice Pro Plus 2019) I am getting an error object stating:
{dataType: null, error: 'Unsupported file type!'}

For example, this is a freshly generated Email, just showing "Text" in the subject and body line. This results in an error.
However, if I try to parse real Emails from customers, including attachments and lots of correspondence, the parsing mostly works fine. 

Hope anyone can help me out here. 
Thank you for your hard work. I really appreciate it.

![header](https://user-images.githubusercontent.com/37910137/205178354-5821dfd8-1306-464e-9d1a-0e122a507767.PNG)
![mail](https://user-images.githubusercontent.com/37910137/205178492-f61c384a-4c88-4725-b4bb-32c1b0d4041a.PNG)

**Comment by kenjiuno** [comment]
Hi.

> {dataType: null, error: 'Unsupported file type!'}

This error will be issued, when the file signature doesn't match with pre defined one.

![2022-12-02_10h28_57](https://user-images.githubusercontent.com/5955540/205194152-4d5deafe-0d9e-4303-a788-4386630d27f0.png)

If you don't mind, please send me a sample msg file to ku@digitaldolphins.jp for detail inspection?
If you send it with Outlook, please archive msg file to `zip`.

**Comment by kenjiuno** [comment]
Hi.
Sorry for late reply.
I got your mail in spam folder.

`Test.msg` has no problem. It is readable.

Also, _online demo_ could decode it. https://hiraokahypertools.github.io/msgreader_demo/

I suspect _msgFileBuffer_ (MsgReader constructor parameter) didn't store correct msg content.

```js
const msgFileBuffer = fs.readFileSync('./data/test.msg')
const testMsg = new MsgReader(msgFileBuffer)
```

For now I have no more information to guess about this issue.

If you have interested in that online demo, you can check the source code:

https://github.com/HiraokaHyperTools/msgreader_demo/blob/c8e01d56a44cf4196b85fb8135b97307aa43d56c/src/index.ts#L132

**Comment by Keanottesen** [comment]
I have the same issue
