### ISSUE TITLE
FieldsData body produces null character?

### ISSUE THREAD

**Issue by PixelsByLucas** [HiraokaHyperTools/msgreader#34]
Is it possible that FieldsData body can produce a null character like "\u0000" instead of the actual email body?

I noticed this in my logs from a PostgreSQL exception: invalid byte sequence for encoding "UTF8": 0x00.  This is caused by trying to insert a null character into a text field.  The value I was trying to insert was coming from FieldsData body.
I noticed that the same email will sometimes produce this result, while other times the body is parsed fine and everything works as expected.  Also when this issue happens, other data like messageDeliveryTime & recipients is parsed correctly.

Any idea what could be causing this?

**Comment by kenjiuno** [comment]
Do you mention `body` about this body? https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.FieldsData.html#body

Including null character in body can be possible in considerable reasons.

- The original msg file body contains any null characters.
- Bug of msgreader.

Including null character in body might be edge case.

msgreader introduces value comparison tests.
Compare JSON files that are made by property key-values extracted from msg file.
https://github.com/HiraokaHyperTools/msgreader/tree/master/test
Currently there is no known case of including null character in body .

If you have enough time to check this case,
you can try another msg parser library like [msg-parser - npm](https://www.npmjs.com/package/msg-parser)

If you want to browse direct content of msg file,
7-Zip File Manager for Windows is the best tool to explore.

![2023-01-13_13h58_53](https://user-images.githubusercontent.com/5955540/212241018-a89f88a8-3e91-4742-86f4-22317f3288f8.png)

Select `__substg1.0_1000001F` and type <kbd>F3</kbd> key to launch notepad or such.

![2023-01-13_13h58_58](https://user-images.githubusercontent.com/5955540/212241046-f1f63d5e-c248-40da-9d0a-6af2672e4934.png)

Reading the `__substg1.0_1000001F`  file with binary editor may help to ident problems.

![2023-01-13_14h03_38](https://user-images.githubusercontent.com/5955540/212241544-ab911129-bbf1-43ee-b0a9-83e2dcbff521.png)

Property type of `__substg1.0_1000001F` is `PtypString`. It is a string of [Unicode](https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcdata/f6f9e26f-ad62-4765-ae9d-0f1c6840d7e9#gt_c305d0ab-8b94-461a-bd76-13b40cb8c4d8) characters in [UTF-16LE](https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcdata/f6f9e26f-ad62-4765-ae9d-0f1c6840d7e9#gt_69864bcc-33be-41c9-9486-e18618ee3dd0) format encoding.
[[MS-OXCDATA]: Property Data Types | Microsoft Learn](https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcdata/0c77892e-288e-435a-9c49-be1c20c7afdb)
