### ISSUE TITLE
Bad RTF produced?

### ISSUE THREAD

**Issue by eduardomb08** [HiraokaHyperTools/msgreader#41]
Hi,

I'm working with both msgreader and rtf-stream-parser and am encountering an issue for certain .msg files.

Although msgreader does produce a result (meaning it doesn't just blow up), the result looks significantly different between two attempts trying to produce a sharable .msg to reproduce the issue.

Could you please take a look at the issue reported below and provide your thoughts as if the msgreader results look like what would be expected?

[Not encapsulated HTML or text file](https://github.com/mazira/rtf-stream-parser/issues/13#issuecomment-1756205893)

Thanks in advance,

Eduardo Monteiro de Barros

**Comment by kenjiuno** [comment]
Hi.

There is an demo site of combination of both msgreader and rtf-stream-parser.

https://hiraokahypertools.github.io/msgreader_demo3/

Is same error reproducible with this version too?

**Comment by eduardomb08** [comment]
> Hi.
> 
> There is an demo site of combination of both msgreader and rtf-stream-parser.
> 
> https://hiraokahypertools.github.io/msgreader_demo3/
> 
> Is same error reproducible with this version too?

Yes:

<img width="329" alt="image" src="https://github.com/HiraokaHyperTools/msgreader/assets/11743735/a20d2d98-dcb7-46dc-9046-bbc64ecd4643">

**Comment by kenjiuno** [comment]
Ok, and then next...
With decoded `.rtf` file, can Microsoft Word open it?

At first obtain `file.rtf` file by clicking `Download` link of RTF section from web browser:

![2023-10-11_12h11_08](https://github.com/HiraokaHyperTools/msgreader/assets/5955540/d1943685-77eb-491a-830a-360ac14d2645)

Open the `file.rtf` with Microsoft Word:

![2023-10-11_12h12_58](https://github.com/HiraokaHyperTools/msgreader/assets/5955540/a4437c8b-e4c1-448d-826f-4d5095f7183f)

If rtf file is valid, Word will open and render it.

![2023-10-11_12h13_46](https://github.com/HiraokaHyperTools/msgreader/assets/5955540/193ad4d1-42d5-4e86-89ed-14d6e999e624)

**Comment by eduardomb08** [comment]
> Ok, and then next... With decoded `.rtf` file, can Microsoft Word open it?
> 
> At first obtain `file.rtf` file by clicking `Download` link of RTF section from web browser:
> 
> 
> Open the `file.rtf` with Microsoft Word:
> 
> 
> If rtf file is valid, Word will open and render it.
> 

Ok. I've downloaded the RTF. Here is what it looks like in Word:

<img width="964" alt="image" src="https://github.com/HiraokaHyperTools/msgreader/assets/11743735/e0e84ea9-6cb7-4f59-9a13-b7b607908994">

**Comment by kenjiuno** [comment]
> Ok. I've downloaded the RTF. Here is what it looks like in Word:

It looks like that plain HTML was pasted in the RTF file.
Is it expected?

**Comment by eduardomb08** [comment]
> > Ok. I've downloaded the RTF. Here is what it looks like in Word:
> 
> It looks like that plain HTML was pasted in the RTF file. Is it expected?

That's what's returned by msgreader (even using demo3):

![image](https://github.com/HiraokaHyperTools/msgreader/assets/11743735/dabcd1f8-245f-443f-81c3-70c48ea58adc)

**Comment by kenjiuno** [comment]
> That's what's returned by msgreader (even using demo3):

According to input from you, this error `Error: Not encapsulated HTML or Text file` is possible.

Encapsulated HTML will represent embedded HTML tag like `{\*\htmltag <html>}`

If `\htmltag` control word is missing, it is just plain text document, and not Encapsulated HTML.

I suspect that msg file isn't generated by Microsoft Outlook.

If it is really plain text, `\fromtext` control word is inserted instead.

![2023-10-12_20h10_55](https://github.com/HiraokaHyperTools/msgreader/assets/5955540/9245b9b2-5d1f-42af-b522-75bfc8636aa7)


Can Microsoft Outlook display the msg file content as expected?

**Comment by eduardomb08** [comment]
> > That's what's returned by msgreader (even using demo3):
> 
> According to input from you, this error `Error: Not encapsulated HTML or Text file` is possible.
> 
> 
> If `\htmltag` control word is missing, it is just plain text document, and not Encapsulated HTML.
> 
> I suspect that msg file isn't generated by Microsoft Outlook.
> 
> If it is really plain text, `\fromtext` control word is inserted instead.
> 
> 
> Can Microsoft Outlook display the msg file content as expected?

Yes, it can:

![image](https://github.com/HiraokaHyperTools/msgreader/assets/11743735/61d163f8-d284-4aab-bcd0-ea6634bef051)

**Comment by kenjiuno** [comment]
> Yes, it can:

Hmm. I'm sorry that I cannot determine what part is malfunctional, for now.

![2023-10-13_17h23_43](https://github.com/HiraokaHyperTools/msgreader/assets/5955540/e0bca00d-5465-4323-b0c0-17b3274fad90)

**Comment by eduardomb08** [comment]
> > Yes, it can:
> 
> Hmm. I'm sorry that I cannot determine what part is malfunctional, for now.
> 

I see if I can find time this weekend to clone the repo and take a look. Do you have any tips?

**Comment by eduardomb08** [comment]
> > Yes, it can:
> 
> Hmm. I'm sorry that I cannot determine what part is malfunctional, for now.
> 

Got it running locally. If you have any tips on how to debug it that would be really helpful:

![image](https://github.com/HiraokaHyperTools/msgreader/assets/11743735/040bb3ad-cd14-46c3-89d1-af34755633ba)

**Comment by kenjiuno** [comment]
> Got it running locally. If you have any tips on how to debug it that would be really helpful:

In order to compare, it is better to search _another implementation_ of msg file reader that is published as open source, rather than msgreader and JavaScript...

![2023-10-16_11h00_33](https://github.com/HiraokaHyperTools/msgreader/assets/5955540/ea0c13f4-6cce-43a3-be58-f0d5ede5c4a5)

**Comment by FROGGS** [comment]
Hi, I'm not sure this is a bug at all.
I'm using msgreader to render emails to html to display them an a webpage for a document managment system.

My code looks like this:
```javascript
    this.msgReader = new MsgReader(buf);
    var fileData  = this.msgReader.getFileData();

 
    if (fileData.compressedRtf && fileData.compressedRtf.length > 8) {
      // mail is rtf-encoded
    }

    else if (fileData.bodyHtml) {
      // mail is already in html format
    }

    else if(fileData.body) {
      // mail is plain text only
    }
```
And why do I do this? Because Outlook saves emails in one of the three formats:
![image](https://github.com/HiraokaHyperTools/msgreader/assets/141968/41906ce3-a743-4f78-b4f5-a72bd06f4a94)

This means that while Outlook can display emails with html-in-rtf, Word does not.
Word needs proper rtf encoded data, not just html wrapped in an rtf envelope.

**Comment by eduardomb08** [comment]
> Hi, I'm not sure this is a bug at all. I'm using msgreader to render emails to html to display them an a webpage for a document managment system.
> 
> My code looks like this:
> 
> ```js
>     this.msgReader = new MsgReader(buf);
>     var fileData  = this.msgReader.getFileData();
> 
>  
>     if (fileData.compressedRtf && fileData.compressedRtf.length > 8) {
>       // mail is rtf-encoded
>     }
> 
>     else if (fileData.bodyHtml) {
>       // mail is already in html format
>     }
> 
>     else if(fileData.body) {
>       // mail is plain text only
>     }
> ```
> 
> And why do I do this? Because Outlook saves emails in one of the three formats: 
> 
> This means that while Outlook can display emails with html-in-rtf, Word does not. Word needs proper rtf encoded data, not just html wrapped in an rtf envelope.

@FROGGS , the image I attached in [this comment](https://github.com/HiraokaHyperTools/msgreader/issues/41#issuecomment-1761627101) above shows the compressedRtf value for my msg. It would satisfy your first if condition for rtf-encoded e-mails, but the library isn't able to process it.

I'm not saying this means it is a bug. Maybe it's just some edge case or exception to what the library is capable of processing. But it would be nice if there were a way to improve it to handle this case too.

**Comment by FROGGS** [comment]
Maybe this is about the used Outlook version? Can you produce another msg-file which you can share perhaps?

**Comment by kenjiuno** [comment]
If you are interested in, you can test this alternative one for comparison with this msgreader. 

https://hiraokahypertools.github.io/msgreader_net_demo/

This is built on _ASP.NET Core Blazor WebAssembly_. Thus there is no backend server for this.

If html output is available BodyHtml may appear.

![2023-10-17_22h38_23](https://github.com/HiraokaHyperTools/msgreader/assets/5955540/448c1f92-6dcc-4062-9ef9-cc9e40e24de0)

**Comment by eduardomb08** [comment]
> If you are interested in, you can test this alternative one for comparison with this msgreader.
> 
> https://hiraokahypertools.github.io/msgreader_net_demo/
> 
> This is built on _ASP.NET Core Blazor WebAssembly_. Thus there is no backend server for this.
> 
> If html output is available BodyHtml may appear.
> 

Looks the same:

![image](https://github.com/HiraokaHyperTools/msgreader/assets/11743735/a3d84f5f-aa0f-485a-8795-26a22436bdf6)

I'll look for another .msg that I can share.
