### ISSUE TITLE
How to get the attachment contentType?

### ISSUE THREAD

**Issue by katlim-br** [HiraokaHyperTools/msgreader#42]

**Comment by kenjiuno** [comment]
Try `@kenjiuno/msgreader@1.21.0-alpha1`

`attachMimeTag` is available now: [SomeOxProps | @kenjiuno/msgreader - v1.21.0-alpha1](https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.SomeOxProps.html#attachMimeTag)

demo site updated too: https://hiraokahypertools.github.io/msgreader_demo/

**Comment by katlim-br** [comment]
Thanks, I'll try that.

Any expectation about when will this become an official version? (kind of uncomfortable to use an alpha release in prod)

**Comment by kenjiuno** [comment]
I'll release retail version when there is no more thing to tweak 👍
