### ISSUE TITLE
How to get MessageID?

### ISSUE THREAD

**Issue by markb-trustifi** [HiraokaHyperTools/msgreader#44]
https://learn.microsoft.com/en-us/office/client-developer/outlook/mapi/pidtaginternetmessageid-canonical-property
https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxtnef/c0c97914-13b1-4a2b-9daf-56a833d433f6

Right now to obtain it we have to regex `headers` or enable `rawProps` and filter property with tag `1035001f` which is not convenient.

**Comment by kenjiuno** [comment]
Thanks for reporting.
`@kenjiuno/msgreader@1.22.0-beta1` has been published.

`messageId` is available.

[FieldsData | @kenjiuno/msgreader - v1.22.0-beta1](https://hiraokahypertools.github.io/msgreader/typedoc/interfaces/MsgReader.FieldsData.html#messageId)
