### ISSUE TITLE
Unexpected apptStartWhole, apptEndWhole, clipStart & clipEnd values

### ISSUE THREAD

**Issue by PixelsByLucas** [HiraokaHyperTools/msgreader#50]
When parsing an IPM.Appointment in msgreader 1.22.0 I noticed some strange behavior regarding the following FieldsData values returned from getFileData: apptEndWhole, apptStartWhole, clipEnd and clipStart.

The values are as follows:
```
apptEndWhole: "Tue, 17 Dec 2024 14:00:00 GMT"
apptStartWhole: "Tue, 17 Dec 2024 12:30:00 GMT"
clipEnd: "Thu, 05 Dec 2024 14:00:00 GMT"
clipStart: "Thu, 05 Dec 2024 12:30:00 GMT"
messageClass: "IPM.Appointment"
```
(also there is no apptRecur property, indicating that it is not a recurring series)

**I'm confused by these values because for single instance appointments I expect:** 
`(apptStartWhole === clipStart && apptEndWhole === clipEnd) // true`
**And for recurring series I expect:**
clipStart/clipEnd to be midnight of the first/last instance in the series in UTC.
**Neither of these appear to be true.**

**Some more clues**
- When the appointment is opened in outlook, the start time & end time are rendered as the above apptStartWhole & apptEndWhole values.
- I was told by the person who created the appointment that the above clipStart/clipEnd values are the same as the date the appointment was originally scheduled for.  And the above apptStartWhole/apptEndWhole values are the same as the date the appointment was changed to after it was edited.  (But in my understanding of these properties, this is not how they should behave).

Can you help explain what I'm seeing here?  Is it a bug with msgreader?  Or perhaps I misunderstand how the properties are meant to behave.

**Comment by kenjiuno** [comment]
At first, most _values_ extracted from msg files are provided _as-is_.

`apptStartWhole`, `apptEndWhole`, `clipStart`, and `clipEnd` are provided as-is without special interpretation.
https://github.com/HiraokaHyperTools/msgreader/blob/cb440b595310145668c1357b11e9c52778bd7650/src/const.ts#L129-L132

Here are special properties processed with msgreader (`apptRecur` is included in this case):

https://github.com/HiraokaHyperTools/msgreader/blob/cb440b595310145668c1357b11e9c52778bd7650/src/MsgReader.ts#L1506-L1551

So, if an MSG file has irregular data, there may be a problem with the export process of the MSG file (using Outlook?).

There may be an edge case that brings export of invalid msg file data, but I cannot figure out what it is.

And also, this method won't work correctly, if there is an invalid msg file like this case.

> **I'm confused by these values because for single instance appointments I expect:**
> `(apptStartWhole === clipStart && apptEndWhole === clipEnd) // true`

Checking existence of `apptRecur`, `clipStart`, and `clipEnd` properties may be better.

**Comment by PixelsByLucas** [comment]
Actually I think what I was complaining about here is expected behavior.

After  doing some more reading in [MS-OXOCAL], it seems the following assumption is not necessarily true. 

> (apptStartWhole === clipStart && apptEndWhole === clipEnd) // true

I'm still not 100% clear on the details, but with single instance appointments, it seems these dates can be different if the appointment's start/end times have been modified.  It seems apptStartWhole/apptEndWhole will sometimes represent the appointment's start/end time of the most recent edit.  When this occurs, clipStart/clipEnd will represent the previously selected appointment start/end time.
