### ISSUE TITLE
Cannot detect if a recipient is TO, CC or BCC

### ISSUE THREAD

**Issue by bahamut657** [HiraokaHyperTools/msgreader#7]
It seems that parsing a MSG file, result in a plain list of recipients, but there is no parameter do know if it is part of TO field, CC field or BCC field.
Is it possible to add a parameter to qualify each recipient?
Regards

**Comment by kenjiuno** [comment]
Ok I'll check it later

**Comment by kenjiuno** [comment]
The published v1.4.0 will decode [PidTagRecipientType](https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/pidtagrecipienttype-canonical-property) which is written in `__recip_version1.0_#00000000/__properties_version1.0` document.

![2020-09-28_21h29_04](https://user-images.githubusercontent.com/5955540/94432402-af8d5580-01d1-11eb-8d1c-5bf123ca1075.png)

**Comment by bahamut657** [comment]
How to download version 1.4.0? I can see only the 1.3.0 on GitHub

**Comment by kenjiuno** [comment]
Sorry, I forgot to push tags.
It is now available: https://github.com/HiraokaHyperTools/msgreader/releases/tag/v1.4.0

**Comment by bahamut657** [comment]
Thanks a lot. It works like a charm.
You can close the issue

**Comment by kenjiuno** [comment]
Thx!
