### ISSUE TITLE
Sent email doesn't contain timestamp

### ISSUE THREAD

**Issue by rtarling** [HiraokaHyperTools/msgreader#9]
Hi

If I drag a sent email from Outlook to the desktop and then pars it using the reader it doesn't contain the sent timestamp anywhere.  However if I look at it using a tool like https://www.encryptomatic.com/viewer/ then I can see the timestamp.

This is quite a critical bug for me so I really hope you can fix it.

I can't attach the file as .msg isn't supported - let me know how I can get it to you so you can take a look.

Thanks
Roland

**Comment by kenjiuno** [comment]
Hi thanks for contacting!

According to request from you, I'm investigating the source of sent time included in msg file.

Currently I don't identify the source of sent time yet.

I wrote a dump command. However it seems to be hidden in undocumented part.

![2021-02-09_20h59_46](https://user-images.githubusercontent.com/5955540/107360785-c34eae00-6b19-11eb-8450-eaeadab68f08.png)

This will take some while.

**Comment by rtarling** [comment]
Hi

Thanks for the quick reply.

Attached is the test file MSG which is causing me problems – it is taken from the Sent folder in Outlook.

Also the From: address is missing, but the online tool I use also can’t see it (below), so I guess it isn’t present in the file.

From:

Roland Tarling

To:

roland.tarling@gmail.com<mailto:roland.tarling@gmail.com>

Sent time:

08 Feb, 2021 12:39:26 PM



Really appreciate your help.  If you have any questions or need any help, just let me know.

Thanks
Roland

**Comment by kenjiuno** [comment]
Ok, v1.5.0 https://www.npmjs.com/package/@kenjiuno/msgreader/v/1.5.0 will decode some dates.

`clientSubmitTime` will be suitable.

![2021-02-15_17h54_33](https://user-images.githubusercontent.com/5955540/107925148-6179c280-6fb7-11eb-898e-27e5d09731d5.png)

**Comment by rtarling** [comment]
Many thanks.  I will try it out tomorrow.  Really appreciate your help and quick turnaround.

**Comment by rtarling** [comment]
Hi

It works perfectly.  Many thanks for this.  I will test it thoroughly over the next few weeks and let you know if I find anything else.

Kind Regards
Roland

**Comment by rtarling** [comment]
Hi

Before I raise it on GitHub, can you please tell me if this is by design.  It doesn’t look right to me.  To reproduce:


  1.  I create an email in Outlook and send it.
  2.  I drag the email from Sent and process it through the MsgReader code.

I see these values when I look at the msg.senderEmail and msg.senderName fields.

  1.  senderEmail: "/o=WinUKMail/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=234322d6fb84499aa3b0cebd535e97c8-19ocs366330"
  2.  senderName: roland.tarling@rolandconsulting.com<mailto:roland.tarling@rolandconsulting.com>

Yours ever / Mit freundlichen Gruessen
Roland Tarling

Mobile :   +41 799 55 4974
Landline: +41 43 535 6167
UK:            +44 203 445 5759 (routes to my Swiss mobile)

**Comment by kenjiuno** [comment]
Hi. You can always raise new issue for another problem.

> I see these values when I look at the msg.senderEmail and msg.senderName fields.

Although I'm not familiar with Microsoft Exchange server side products, it seems `LegacyExchangeDN` is used in `senderEmail`.

The source of props:

- `senderEmail`: [PidTagSenderEmailAddress Canonical Property | Microsoft Docs](https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/pidtagsenderemailaddress-canonical-property)
- `senderName`: [PidTagSenderName Canonical Property | Microsoft Docs](https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/pidtagsendername-canonical-property)

Was the mail delivered thru Exchange server not SMTP server?

The transport type is recorded in property: [PidTagSentRepresentingAddressType Canonical Property | Microsoft Docs](https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/pidtagsentrepresentingaddresstype-canonical-property).

You can extract it with 7-Zip. Open msg file with 7-Zip. And then check contents of `__substg1.0_0064001F` file using notepad or such. `SMTP` or `EX` will be recorded.
